name: Deploy Redis Container

on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: self-hosted   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 
          docker build --security=insecure -t tresorkangone/redis:latest .


      - name: Push Docker image
        run: |
          docker push tresorkangone/redis:latest

      - name: Deploy container
        run: |
          docker stop redis || true
          docker rm redis || true
          docker run -d --name redis -p 6379:6379 tresorkangone/redis:latest
